import { readFile } from "node:fs/promises";
import { agentPath } from "../core/paths.ts";
import { repoCommit, stableHash, nowIso } from "../core/provenance.ts";
import { writeJson } from "../core/artifact-writer.ts";
import type { Finding, ToolRunRecord } from "../core/types.ts";
import { detectCommand, runTool } from "./tool-runner.ts";

export async function detectOpenGrep() {
  return detectCommand("opengrep", ["sast", "json-output", "sarif-output"]);
}

export async function runOpenGrep(repo: string): Promise<{ findings: Finding[]; toolRun: ToolRunRecord | null; unavailable?: string }> {
  const rawPath = agentPath(repo, "findings", "raw", "opengrep.json");
  const capability = await detectOpenGrep();
  if (!capability.available) {
    await writeJson(rawPath, { unavailable: true, reason: capability.reason, results: [] });
    return { findings: [], toolRun: null, unavailable: capability.reason };
  }
  const run = await runTool(repo, "opengrep", ["opengrep", "scan", "--json", "--quiet", "--exclude=.codetree", "--exclude=.gitnexus", "."], rawPath);
  let raw: unknown;
  try {
    raw = JSON.parse(run.stdout || "{}");
  } catch {
    raw = { parse_error: true, stdout_preview: run.stdout.slice(0, 1000), stderr_preview: run.stderr.slice(0, 1000), results: [] };
  }
  await writeJson(rawPath, raw);
  return { findings: await normalizeOpenGrep(repo, rawPath), toolRun: run.record };
}

async function normalizeOpenGrep(repo: string, rawPath: string): Promise<Finding[]> {
  const raw = JSON.parse(await readFile(rawPath, "utf8"));
  const results: any[] = Array.isArray(raw.results) ? raw.results : [];
  const commit = await repoCommit(repo);
  return results
    .filter((result: any) => {
      const p = result.path ?? result.extra?.path ?? result.locations?.[0]?.physicalLocation?.artifactLocation?.uri ?? "";
      if (p.includes(".security-agent/")) return false;
      return true;
    })
    .map((result: any): Finding => {
    const path = result.path ?? result.extra?.path ?? result.locations?.[0]?.physicalLocation?.artifactLocation?.uri ?? "unknown";
    const line = Number(result.start?.line ?? result.locations?.[0]?.physicalLocation?.region?.startLine ?? 1);
    const ruleId = String(result.check_id ?? result.ruleId ?? "opengrep-rule");
    const message = String(result.extra?.message ?? result.message?.text ?? ruleId);
    const severity = mapSeverity(result.extra?.severity ?? result.level);
    const key = stableHash(["opengrep", ruleId, path, line, message].join("|"));
    return {
      id: `finding-${key.slice(0, 16)}`,
      title: message.slice(0, 120),
      bug_class: classifyRule(ruleId, message),
      severity_claim: severity,
      confidence: "medium",
      stage: "discovery",
      source_agent: "opengrep-sast-agent",
      tool: "opengrep",
      external_source: "none",
      external_status: "none",
      files: [{ path, start_line: line, end_line: Number(result.end?.line ?? line) }],
      entrypoint: { type: "unknown", name: "unknown", reachable: false, evidence: "OpenGrep does not prove reachability by itself" },
      dataflow: { source: "unknown", sink: ruleId, sanitizers: [], missing_checks: [] },
      evidence: [{ kind: "rule", content: message.slice(0, 500), path, line, provenance: rawPath }],
      reproduction_hint: "Review the referenced source and rule match. No exploit payload generated by MVP.",
      dedup_key: stableHash([classifyRule(ruleId, message), path, line, ruleId].join("|")),
      limitations: ["rule match requires native triage before acceptance"],
      created_at: nowIso(),
      repo_commit: commit
    };
  });
}

function mapSeverity(severity: unknown): Finding["severity_claim"] {
  const value = String(severity ?? "").toLowerCase();
  if (["error", "critical"].includes(value)) return "high";
  if (value === "warning") return "medium";
  if (value === "note") return "low";
  return "medium";
}

function classifyRule(ruleId: string, message: string): Finding["bug_class"] {
  const text = `${ruleId} ${message}`.toLowerCase();
  if (/sql|nosql|ldap|command|injection|ssrf|traversal/.test(text)) return "injection";
  if (/authz|authorization|idor|access.control|tenant/.test(text)) return "authz";
  if (/authn|authentication|jwt|session/.test(text)) return "authn";
  if (/secret|token|credential|password|apikey|api.key/.test(text)) return "secrets";
  if (/crypto|hash|cipher|random|tls|ssl/.test(text)) return "crypto";
  if (/deserialize|yaml|xml|pickle|marshal|prototype/.test(text)) return "deserialization";
  if (/dependency|package|supply/.test(text)) return "dependency";
  if (/config|cors|debug/.test(text)) return "config";
  return "other";
}
